### ISSUE TITLE
plugin[method] is not a function

### ISSUE THREAD

**Issue by jppellerin** [idangozlan/verdaccio-bitbucket#12]
I am getting a TypeError when attempting to login using this plugin.

Here is the error I am getting :

```
TypeError: plugin[method] is not a function
    at next (/usr/local/app/build/lib/auth.js:108:23)
    at Auth.add_user (/usr/local/app/build/lib/auth.js:118:7)
    at /usr/local/app/build/api/endpoint/api/user.js:24:12
    at Layer.handle [as handle_request] (/usr/local/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/app/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/app/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/local/app/node_modules/express/lib/router/index.js:365:14)
 http <-- 500, user: undefined(172.17.0.1), req: 'PUT /-/user/org.couchdb.user:jp.pellerin..gmail.com', error: internal server error
 http <-- 500, user: undefined(172.17.0.1), req: 'PUT /-/user/org.couchdb.user:jp.pellerin..gmail.com', error: internal server error
```

Plugin installed using npm and successfully loaded (`Plugin successfully loaded: bitbucket` on startup).

Any help getting this figured out would be appreciated.  Using verdaccio 3.3.0.

Here is my run command and startup log:
```
$ docker run -it -p 4873:4873 87eb94c3420b
 warn --- config file  - /verdaccio/conf/config.yaml
 warn --- Plugin successfully loaded: s3-storage
 warn --- Plugin successfully loaded: bitbucket
 warn --- Plugin successfully loaded: audit
 warn --- http address - http://0.0.0.0:4873/ - verdaccio/3.3.0
```

**Comment by juanpicado** [comment]
Agree with @oeph

**Comment by idangozlan** [comment]
Please try the latest version of Verdaccio.
